---
abstract: 'A Bind DNS zone file generator'
author:
  - 'Daniel P. Berrange <dan.com>'
build_requires:
  File::Temp: 0
  Test::More: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
configure_requires:
  Module::Build: 0.4
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: NoZone
provides:
  NoZone:
    file: lib/NoZone.pm
    version: 1.0
  NoZone::Zone:
    file: lib/NoZone/Zone.pm
    version: 0
requires:
  Config::Record: v1.1.2
  File::Spec::Functions: 0
  perl: v5.6.0
resources:
  license: http://www.gnu.org/licenses/old-licenses/gpl-1.0.txt
version: 1.0
